In [8]:
import numpy as np


a = np.array([[1, 2], [3, 4]])
print("2D Array:", a)

# Convert 2D → 1D
one_d = a.reshape(4)   
print("1D Array:", one_d)

# Convert 2D → 3D
three_d = a.reshape(2, 2, 1)  
print("3D Array:", three_d)


2D Array: [[1 2]
 [3 4]]
1D Array: [1 2 3 4]
3D Array: [[[1]
  [2]]

 [[3]
  [4]]]


In [16]:
import numpy as np

a = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

print("Original 3D:", a)
shape = a.reshape(4,3)
print("2D:",shape)
  


b = a.reshape(12)  
print("Converted 1D:", b)




Original 3D: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2D: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Converted 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]
